# Generated by Django 5.2.7 on 2025-12-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionhistory',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='predictionhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
